# 项目相关配置
portal:
  author: codex
  name: netdisk-portal
  version: 1.0
  # 文件上传路径
  profile: /Users/codex/Workspace/uploadPath/netdisk

# 开发环境配置
server:
  # 服务器端口
  port: 9001
  servlet:
    # 应用访问路径
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      # 最大线程数，默认值200
      max: 800
      # tomcat启动初始化的线程数，默认值25
      min-spare: 30

# spring
spring:
  profiles:
    active:
      - druid
      - redis
      - mp
#    include: druid,redis,mp
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      # 单个文件大小，10G
      max-file-size: 10240MB
      # 设置总上传的文件大小，1T
      max-request-size: 1048576MB

# PageHelper配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

# 日志配置
logging:
  level:
    cn.codex: debug
    org.springframework: warn

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
  setting:
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Copyright© 2021 舟意网盘